/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kyuty_jnidemo_MyNDK */

#ifndef _Included_com_kyuty_jnidemo_MyNDK
#define _Included_com_kyuty_jnidemo_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kyuty_jnidemo_MyNDK
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kyuty_jnidemo_MyNDK_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
